#!/bin/bash
#
#SBATCH --job-name=version02weak
#SBATCH --output=version02weak.txt
#
#SBATCH -N 11 # number of nodes
#SBATCH -n 128 # number of cores
#SBATCH --partition=nodo.q
#SBATCH --exclusive
#SBATCH --nodelist=clus[01-06,08-12]

module load openmpi/3.0.0
module load gcc/8.2.0
cd ../src

make realclean
make all version=02

rm -f ../data/weak/version02.txt

size=512
for ((i=4;i<=128; i*=2))
do
    mpirun -np ${i} lap ${size} 100 >> ../data/weak/version02.txt
    size=$(($size*2))
done
